# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OMDB Search' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OMDB Search
  pod 'KRLCollectionViewGridLayout', '~> 0.4'
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.2'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'CCBottomRefreshControl', '~> 0.5'

end
